service: nasa-space-connect
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler
    events:
    - schedule: 
      rate: rate(10 minutes) 
    environment:
    apikey: DEMO_KEY
    Twilio_Account_SID: ACb5ed719abfce2140535e546d85802749
    Twilio_Auth_Token: 55002b9c418f8c64ab66a913c2b99a95
    Twilio_phone_Number: +12294045728
    Personal_nomber: +919708132091